### ISSUE TITLE
"Personalize your CSS" is not working with landing page css (landing.css).

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#120]
"Personalize your CSS" is not working with landing page css (landing.css).

**Comment by ildyria** [comment]
That's because `user.css` is not included in the landing / pages.
If you want to add it, you can make a PR where you modify:
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/resources/views/landing.blade.php
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/resources/views/page.blade.php

**Comment by SerenaButler** [comment]
I'll try :-D
