### ISSUE TITLE
Album View // Album About // Owner should not be shown when not logged in (Security)

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#137]
When not logged in the Album Owner (Usually an Admin) should not be shown to the public in the About Sidebar.

**Comment by d7415** [comment]
I'm not sure how I feel about this. Labelling it a security issue definitely seems overkill.

**Comment by d7415** [comment]
Also, cross-reference #138

**Comment by SerenaButler** [comment]
To get one component of an account, the admin name on a silvertablet IS a security issue ;-)

**Comment by d7415** [comment]
Sure. A very, very minor security issue. If you're relying on your username for security, you're doing it wrong. Especially if you're relying on your username and leaving it as the default as in your screenshots ;)

**Comment by ildyria** [comment]
One thing, when showing "admin" as owner, it does not means that the login to log is actually admin. Both username and password of the admin account are actually hashed. There is no way to retrieve that username (as opposed to the other usernames).

**Comment by d7415** [comment]
So this doesn't apply to the admin account. I think if there are multiple users uploading, knowing who uploaded them would be useful.

We could potentially store a "Display Name" for each user. That would solve this and give a more meaningful output for admin users.

Otherwise I'm inclined to mark this `wontfix`.
