### ISSUE TITLE
Migrating from v3 to v4 is broken

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee-Laravel#144]
The usual process is install Laravel, migrate and then move the pictures.

However with the hidpi migration, it is broken. The migration tries to find pictures that are not there and thus crashes.

@kamil4 you may want to have a look at that one. :)

**Comment by kamil4** [comment]
I never tried migrating an existing installation from v3 to v4. Are you saying that it crashes when running `php artisan migrate` because the image files are not where they are supposed to be?

Crashing is of course not good and should be fixed but in general, my recommendation would be to move the pictures before running the database migration. :smiley: The code needs to access the pictures to query their sizes, which are then put in the database. I guess if a picture is not found, I'll need to enter in the database that it's simply not available, forcing the use of `big`. The user should then regenerate the intermediate sizes later using `php artisan generate_thumbs`...

**Comment by ildyria** [comment]
true.

Or a warning telling them that the picture was not found. :)
