### ISSUE TITLE
Option to make "Recents" folder public

### ISSUE THREAD

**Issue by ABLomas** [LycheeOrg/Lychee-Laravel#176]
For now, other (unregistered) users have no tools to track albums. No RSS, no other streams and if there are sub-albums, even with "sort-by-date" - need to go into each and check if there is anything new on top.
As admin user we have "smart-album" called "Recent", it holds latest uploaded photos automatically. But it's not public and no option to make it public.
Maybe add option (may be available in "Settings -> More" option, to keep settings GUI unmodified) to make it public and "days for recent" configurable?
This would allow people to "follow" albums.

**Comment by ildyria** [comment]
First of all:
- RSS feed is planned: #39 
- Search by date is planned: #50 

> Maybe add option (may be available in "Settings -> More" option, to keep settings GUI unmodified) to make it public and "days for recent" configurable?

I like this idea, the number of days should be easily doable.
+ Need to be edited: https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Photo.php#L330
+ a migration file (`php artisan make:migration add_number_days_recent`).

As for making it public, this one is slightly more tricky as you may not want all your pictures to be public. This requires to check if the album containing the picture is private or not...

**Comment by ABLomas** [comment]
Thanks, as a workaround (unsafe - but i do not have non-public albums) i tried to change line 172 in ./app/ModelFunctions/PhotoFunctions.php (public = 1) - then "Recents" album can be accessed by using URL #r
But it's not shown in album list. This is better than nothing (can pass URL and people can access it for updates) but if i can display it in album list without big changes - would be even better. Any hints? Maybe i should add album ID?
(just to repeat - i know that it would display all pictures, including non-public, but this is not a problem for me, as i do not have non-public pics).

**Comment by kamil4** [comment]
I'm surprised to hear that modifying https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/ModelFunctions/PhotoFunctions.php#L172 had any effect for you. That code is used when uploading new pictures, not when viewing.

Making it viewable will not be a one-line patch...

The code that determines whether smart albums are in the albums list is here: https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Http/Controllers/AlbumsController.php#L57-L64. You'll need to comment out everything but line 62. The invoked `getSmartAlbums` function (https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/ModelFunctions/AlbumFunctions.php#L233-L271) will need to be modified as well so that it doesn't filter by user ID. I'm guessing that's it for the server part (unless the code also triggers some security checks that need to be disabled).

Then there's the front end that also needs to be changed. At the very least, https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/view.js#L43 will need to be modified. If you're lucky, that may be a one-liner patch, although it will probably need more work to make it look pretty.

**Comment by ABLomas** [comment]
Hmm, at least now, with that one line change "Recent changes" album is visible, you can check:
https://pics.lag.lt/#r

Hmmm, maybe it's visible by default using this link, going to check soon.

And thanks for comments about album visibility, will try soon.

**Comment by kamil4** [comment]
Interesting... You may have identified a minor bug in the current code -- it appears that we unconditionally allow the viewing of smart albums, even if the smart albums themselves should not be enabled (as in the public mode right now). I'll try to resist the temptation of fixing it before we provide proper support for a public Recent. :wink: I just hope it doesn't leak anything...

**Comment by kamil4** [comment]
I saw that @ildyria added a Security label yesterday so I checked it out and it's way more serious than I thought. `#r` basically leaks everybody's recent additions, be they public, hidden, password protected, and even private... We need to get this fixed quickly. @ABLomas, all I can suggest to you is to stay with the version you have until we add the public Recent, but in the meantime we'll have to close this loophole.

**Comment by kamil4** [comment]
FYI, I felt a little guilty about taking that accidental feature away from you so I bumped it to the top of my todo list. I expect it to be ready later this week.

I removed the "good first issue" label since, given the security implications, this one is a little tricky.

**Comment by ABLomas** [comment]
OK, so as a workaround (not good, i know, but still works for me) - keep version below commit which fixes this issue. For "days to show" in recent:
./app/Photo.php, line 451
return self::set_order($query->where('created_at', '>=', Carbon::now()->subDays(1)->toDateTimeString()));
 - change "subDays" to another number (7 for a week, etc).

**Comment by kamil4** [comment]
Yes, that's exactly the way to do it! I already added a config option for it on my devel branch as well.

**Comment by kamil4** [comment]
OK, I pushed an initial implementation of this feature. It needs more testing before I submit PRs so @ABLomas if you want to give it a try:

1. Check out the `public-recent` branches of both Lychee-Laravel and Lychee-front repos.
2. Run database migration (`php artisan migrate`).
3. Recompile the front end (`npm run compile`).
4. Enable the option in Settings/More...

**Comment by ABLomas** [comment]
Oh, was on vacation so missed those changes.
Just updated, working here without issues so far, thanks!
