### ISSUE TITLE
Question: How is the upload folder protected?

### ISSUE THREAD

**Issue by Vorlif** [LycheeOrg/Lychee-Laravel#304]
### Question
Could you perhaps explain to me how the `uploads/` folder is protected from direct access? I'm using Nginx and can access protected files directly via the URL even if I'm logged out. I would like to prevent this but don't understand how you can protect your files with Apache.

If I understand how the files are protected with Apache, I might be able to configure this under Nginx and share this configuration here.

Or is it processed with #296?

**Comment by d7415** [comment]
Short version: It's not protected

Long answer: #295 added some protection through symlinking, so that the URLs used are temporary.
Lychee v3 has a plugin that allows what you seem to want, where the PHP serves the image (or not) after checking access, but that's not currently being worked for v4 as it slows down media access.

A well formed PR with this as an option would probably be accepted, or if there's enough demand we may look into adding this in the future.

**Comment by kamil4** [comment]
To add a bit to @d7415's answer:

Right now, the protection is basically through the use of difficult to guess names (it's an MD5 checksum of the system time at the time of upload). #295 not only made those names temporary (this needs to be enabled in the Settings, BTW) but it also provided optional support for hiding the full-size version (this is only effective with symlinking as without it the URL can be derived from that of intermediate-size images).

@ildyria recenlty posted the following link on how a more effective protection could be implemented: https://bedigit.com/blog/laravel-5-how-to-access-image-uploaded-in-storage-within-view/. He didn't go down that route himself due to performance concerns but I agree that if somebody contributed a clean implementation as an option, we'd probably accept it.

**Comment by Vorlif** [comment]
Thank you for your explanation. The implementation with the symlinks in connection with a high nginx-request-limit should be sufficient for my needs.

Can the performance problem not be bypassed by X-Sendfile or is the implementation not desirable? It is supported by [Apache](https://tn123.org/mod_xsendfile/) and [Nginx](https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/). Unfortunately I don't have any experience with PHP and can't support you.
