### ISSUE TITLE
Album disapears

### ISSUE THREAD

**Issue by mpxgit** [LycheeOrg/Lychee-Laravel#362]
When you add a child album to a parent album the parent album disapears.

1. Go to an album
2. Click on 'the folder icon (move album)'
3. Click on 'new Album'
4. Enter name for the new album 
5. Save
6. The parent album is gone

![Bildschirmfoto 2019-10-03 um 22 48 28](https://user-images.githubusercontent.com/9916035/66163422-9c808d80-e630-11e9-8960-1e51b01c1cc2.png)

If i look into the database a circle connection is added in the album table.
The parent album has the parent id of a child album.

Example from the album table:
(15701303144985,'Parent album',0,15701311583122,'',NULL,NULL,0,1,1,0,NULL,'none','2019-10-03 17:18:34','2019-10-03 17:32:38'),
(15701311583122,'Child album',0,15701303144985,'',NULL,NULL,0,1,1,0,NULL,'none','2019-10-03 17:32:38','2019-10-03 17:32:38');

**Comment by ildyria** [comment]
I guess a "oups" is of order. :'D

**Comment by kamil4** [comment]
Yeah, that sounds pretty nasty... Thanks for the report!

I'm guessing that the albums are still reachable by entering the album id in the browser's URL bar, and once displayed, can probably be moved to the top level, but still...

It's not immediately obvious to me how to fix this though... I think we agreed that the "New album" _should_ be under the current album, not at the top level. Should we simply disable the "New album" option in this case?

**Comment by ildyria** [comment]
Or the New Album has to be created under the root.

**Comment by kamil4** [comment]
Well, as I already said, I believe we had this discussion recently and we agreed then that "New Album" means a subalbum of the current album. Which, now that I think about it, makes sense consistency-wise, since the usual way to create a subalbum is using "New Album" in the "+" menu...

Anyway, I'm fixing this in the front end. "New Album" will not be available when moving the current album.

BTW, my guess that the albums could still be reached turned out to be wrong. They trigger a server error via infinite recursion. Fixing it requires modifying the database directly, changing the parent of one of the albums to `NULL`.

**Comment by mpxgit** [comment]
@kamil4 

> BTW, my guess that the albums could still be reached turned out to be wrong. They trigger a server error via infinite recursion. Fixing it requires modifying the database directly, changing the parent of one of the albums to NULL.

I can confirm setting the parent_id to NULL fixes the problem.
