### ISSUE TITLE
Possibility to disable "full-photo" for public

### ISSUE THREAD

**Issue by hardfire** [LycheeOrg/Lychee-Laravel#6]
I just setup Lychee-Laravel and so far it seems to work pretty well. I have been playing around with it and realized that its a bit weird that public users can see/download a picture in full size/quality. Is it possible to disable this altogether, maybe via a flag or a configuration somewhere?

**Comment by ildyria** [comment]
That seems quite difficult because:
- this would require completely changing the infrastructure in the way we serve images.
- the URL is predictable: even if you don't know the *big* url, you just need to access the *medium* one to find the full size one. :/

But if you have ideas that can be easily implementable without breaking compatibility when doing a `git pull` then I'm totally up for it. :)

**Comment by ildyria** [comment]
@hardfire Done.

The trick is weak because the `big` picture are still exposed but the `full-photo` button is not exposed to the public if you disable it in your advances settings.
