### ISSUE TITLE
Image setting medium_max_width, medium_max_height wrong result (?)

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee-Laravel#99]
medium_max_width is set to 1280, medium_max_height is set to 720 and then to 0. Uploaded image has a width of 1080 x 720 so, what is not I expected ;-)

**Comment by kamil4** [comment]
I'm sorry, I don't quite understand your description; could you elaborate? What do you mean that medium_max_height is set to "720 and then to 0"? What is the value when you upload the image?

Also, can you say what the size of the original image was, and what was the size you expected for the medium image?

**Comment by SerenaButler** [comment]
I wrote a long text ... just to understand **I should read better** AND **I need something different** :-P

What I expect or like to have is a result of 1280 x 853 pixel :-) 

The limitations of e.g. linked images in forums are usually in width not height.  

It's technically fine as it is but It seems I need a **medium_min_width** :-P

I would suggest when e.g. medium_max_height is set to "0" then only medium_max_width is the constraint and it will result in a max width of e.g. 1280px.

**Comment by kamil4** [comment]
OK, I understand now. Yes, we support setting the *width* to 0 (we do that for small_max_width by default) but, having recently messed around that code, I remember noticing that setting the *height* to 0 was not fully supported.
Actually, I think it might already work if you use GD instead of Imagick for image resizing. If you want to give it a try, set imagick in the full settings to 0, medium_max_width to 1280 and medium_max_height to 0, and see if that does what you want.
Either way, I'll try to implement a comprehensive fix this weekend.

**Comment by SerenaButler** [comment]
Checked with GD and you are right that's what I want :-D
